In [33]:
import numpy as np
from scipy.linalg import svd

print("How many rows do you want your matrix to have? ")
rows = input()
print("How many columns do you want your matrix to have? ")
cols = input()

X = np.zeros((int(rows), int(cols)))
for i in range(int(rows)):
    for j in range(int(cols)):
        print("enter the value for row " +str(i)+ " and column " +str(j)+ " : ")
        X[i][j] = input()
        
print(X)

How many rows do you want your matrix to have? 
5
How many columns do you want your matrix to have? 
4
enter the value for row 0 and column 0 : 
1
enter the value for row 0 and column 1 : 
2
enter the value for row 0 and column 2 : 
3
enter the value for row 0 and column 3 : 
4
enter the value for row 1 and column 0 : 
5
enter the value for row 1 and column 1 : 
6
enter the value for row 1 and column 2 : 
7
enter the value for row 1 and column 3 : 
8
enter the value for row 2 and column 0 : 
9
enter the value for row 2 and column 1 : 
0
enter the value for row 2 and column 2 : 
-1
enter the value for row 2 and column 3 : 
-2
enter the value for row 3 and column 0 : 
-3
enter the value for row 3 and column 1 : 
-4
enter the value for row 3 and column 2 : 
-5
enter the value for row 3 and column 3 : 
-6
enter the value for row 4 and column 0 : 
-7
enter the value for row 4 and column 1 : 
-8
enter the value for row 4 and column 2 : 
-9
enter the value for row 4 and column 3 : 
-10
[[  1.

In [34]:
#Step 1

XT = X.transpose()
XTX = np.matmul(XT,X)

In [35]:
#Step 2

eigenvals = np.linalg.eig(XTX)
singular_vals = []
for i in eigenvals[0]:
    if i >= 0:
        singular_vals.append(np.sqrt(i))
    else:
        singular_vals.append(np.sqrt(abs(i)))

In [36]:
#Step 3

singular_vals.sort(reverse = True)

count = 0
for i in singular_vals:
    count += 1
sigma = np.zeros((count, count))

for i in range(count):
    sigma[i][i] = singular_vals[i]

sigma_inv = np.linalg.inv(sigma)

In [37]:
#Step 4

eigenvalues, eigenvectors = np.linalg.eigh(XTX)
sorted_indices = np.argsort(eigenvalues)[::-1]
V = -1*eigenvectors[:, sorted_indices]
VT = V.T

In [38]:
#Step 5 (U=X*V*sigma_inv)

U = np.matmul(X, np.matmul(V, sigma_inv))
A = np.matmul(U, np.matmul(sigma, VT))

print("Original Matrix After SVD:")
print(A)
print("U:")
print(U)
print("Sigma:")
print(sigma)
print("V Transpose:")
print(VT)

Original Matrix After SVD:
[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00]
 [ 5.00000000e+00  6.00000000e+00  7.00000000e+00  8.00000000e+00]
 [ 9.00000000e+00 -1.99797038e-17 -1.00000000e+00 -2.00000000e+00]
 [-3.00000000e+00 -4.00000000e+00 -5.00000000e+00 -6.00000000e+00]
 [-7.00000000e+00 -8.00000000e+00 -9.00000000e+00 -1.00000000e+01]]
U:
[[ 2.18136761e-01 -1.45611557e-01  7.94489539e-01  4.28408384e-07]
 [ 5.45456564e-01 -3.89159682e-02 -3.10271460e-02 -3.72529030e-08]
 [ 7.92378431e-02  9.84155446e-01  1.58617219e-01  1.13621354e-07]
 [-3.81796663e-01  9.22637629e-02 -3.81731197e-01 -1.95577741e-07]
 [-7.09116466e-01 -1.44318264e-02  4.43785489e-01  2.77534127e-07]]
Sigma:
[[2.41742508e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 9.21884303e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.86468191e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.86785994e-08]]
V Transpose:
[[ 4.04056593e-01  4.5127